### ISSUE TITLE
Module not found error

### ISSUE THREAD

**Issue by i001962** [noctisatrae/succus#2]
Tried to test this by creating a react app using cra with nvm use 14, npm i succus, then importing succus and it's exported functions. Getting this error:

ERROR in ./node_modules/succus/dist/index.js 3:0-17
Module not found: Error: Can't resolve 'gun/sea' in '/Users/kmm/Dropbox/aws/gun/succus/node_modules/succus/dist'
Did you mean 'sea.js'?
BREAKING CHANGE: The request 'gun/sea' failed to resolve only because it was resolved as fully specified
(probably because the origin is strict EcmaScript Module, e. g. a module with javascript mimetype, a '*.mjs' file, or a '*.js' file where the package.json contains '"type": "module"').
The extension in the request is mandatory for it to be fully specified.
Add the extension to the request.

**Comment by noctisatrae** [comment]
Weird! Is node v14 the latest LTS version? If not, could you try running your code after installing the LTS version with nvm?

While you do that I'll be investigating on your setup.

Thanks Kmac!

**Comment by i001962** [comment]
Will do in a few hours. Could use sample code for importing and calling functions just to make sure I'm doing it as you'd expect. The docs are ok but still trying to figure out eg assumptions the package makes regarding when and where the gun keypair is created by the embedding app. Eg if already have gun keypair does app need to connectwallet to send msg? Send msg calls connectwallet automatically. Would like to update docs with provider info to help devs understand the assumptions and have a faster start. Will help here after coming up to speed on the implementation.

**Comment by noctisatrae** [comment]
Thanks for the insight! It greatly helps me to improve the overall developer experience and better answer the needs of those users!

Here's a little example:
```js
import { connectWallet, sendmessage, receiveMessageConstant, dbConf } from "succus";

dbConf({
    peers:['https://gun-manhattan.herokuapp.com/gun', 'https://gun-us.herokuapp.com/gun', "https://gunpoint.herokuapp.com/gun"]
})

// i generate a test keypair
const gunKeypair = await SEA.pair();

// I send a message to a test address, replace by your own
await sendmessage("Hi from button", [address], gunKeypair);

// replace the address with any ETH address you want.
await receiveMessageConstant([address], async ({encryptedMSG, date, from, ensFrom}) => {
    const decrypted = await SEA.decrypt(encryptedMSG, gunKeypair);
    await console.log(decrypted)

    // do something with the data like updating the messages for instance.
    await setMessages(prev => [...prev, { content:decrypted, sentAt:date, from: from, name: ensFrom }]);
});
```

**Comment by i001962** [comment]
Closing this as moving to node 16 lts has remedied the situation.
